#pragma checksum "C:\Users\user\source\repos\JobApplicationProj3\JobApplicationProj3\App.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "846F24506AFA125931B609D981935384"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplicationProj3
{
    partial class App : global::Windows.UI.Xaml.Application
    {
    }
}

